- name: nginx - add signing key
  apt_key: url=http://nginx.org/keys/nginx_signing.key state=present

- name: nginx - add sources.list deb url
  lineinfile: dest=/etc/apt/sources.list line="deb http://nginx.org/packages/mainline/ubuntu/ yakkety nginx" # assuming Ubuntu 16.10; use 'trusty' for 14.04

- name: nginx - update apt cache
  apt:
    update_cache: yes

- name: nginx - install nginx
  apt:
    pkg: nginx
    state: latest

- name: nginx - set custom port
  replace:
    dest: /etc/nginx/conf.d/default.conf 
    regexp: '[ ]+(listen)[ ]+80(.)'
    replace: '    \1 8888\2'
    backup: yes

- name: nginx - start nginx
  service:
    name: nginx
    state: started
